### ISSUE TITLE
[Suggestion/Request] Configurable Camera distance between Mouse and Player, preferably with sliders

### ISSUE THREAD

**Issue by Agent3554** [HandsomeMichael/ObamaCamera#1]
Can you make a distance configuration (preferably on sliders) when 'Overhaul Camera' is turned on? The reason is because when the 'Overhaul Camera' overrides Terraria Overhaul's camera system, the overridden camera's distance reach much further compared to Terraria Overhaul's Mouse-cam, as if I'm using a Sniper Scope accessory from vanilla Terraria (except this mod has smooth-cam to go along with it as well)

This mod's camera distance between mouse and player can go very far, and I would like to configure the distance with slider, just so I could match the same distance as Terraria Overhaul's mouse-cam distance as well

**Comment by HandsomeMichael** [comment]
This feature now added in the latest version ( v.0.5 ) as the "Camera Follow Mouse Distance" in the config . thanks for youre feedback to this mod :+1:
