### ISSUE TITLE
Camera screenshake on explosion stopped working on Version 0.6

### ISSUE THREAD

**Issue by Agent3554** [HandsomeMichael/ObamaCamera#2]
Downgrading back to v0.5 somehow fixes that issue

**Comment by Agent3554** [comment]
Reloading the mod twice somehow fixes the issue in v0.6

**Comment by Agent3554** [comment]
Tried testing both version v0.5 and v0.6 noticed significant changes, explosions not working in latest version confirmed

**Comment by HandsomeMichael** [comment]
should be working now on the latest version :+1:
