### ISSUE TITLE
Shake on Roar and Explode breaks the game

### ISSUE THREAD

**Issue by Matt0704** [HandsomeMichael/ObamaCamera#3]
Whenever I try to enable "Shake on Roar and Explode", it makes all sound effects not play, breaks boss transformations, and a lot of projectiles, and a lot of other side effects.
Maybe this is a Calamity thing? Almost all the other configs work.

**Comment by HandsomeMichael** [comment]
Seems like it was the screenshake calamity support that causing the bug. i will remove it in the next update and it should work fine

**Comment by Matt0704** [comment]
Ok it's working fine now.
