### ISSUE TITLE
'Screen Shake On Roar and Explode' doesn't work when Terraria Overhaul is enabled

### ISSUE THREAD

**Issue by Agent3554** [HandsomeMichael/ObamaCamera#4]
Explosions from any source stopped shaking (Onyx Blaster, Grenade, Bomb, Dynamite), and Boss Roars (boss summon item effect & boss attacks with roar sound) stopped working as well

I noticed this when I had Terraria Overhaul enabled, but working fine if it's disabled, and noticed it just now
Previous versions working fine (v0.5 for example) even if it has Terraria Overhaul enabled

**Comment by Agent3554** [comment]
I think I found the issue

Edit: Nvm, got more errors the moment I attempted to integrate 0.5 check method to 0.7.5

**Comment by HandsomeMichael** [comment]
in 0.8 the old code is now merged with the new ones. it should be fix now  :+1:
